### ISSUE TITLE
Exercise 9 activity

### ISSUE THREAD

**Issue by tomdeakin** [codeplaysoftware/syclacademy#120]
The Exercise 9 activity says to look at how Exercises 6 and 8 synchronise, and change to use `.wait()` on the queue itself. However, the current solutions for Exercises 6 and 8 already use `.wait()`.

**Comment by AerialMantis** [comment]
In the solutions for exercises 6 and 8 they are calling `wait` on the events returned from calls to `submit`/`parallel_for`/`memcpy` , so the idea of exercise 9 is to remove those and replace them with calls to `wait` on the queue objects in a separate expression instead.

**Comment by tomdeakin** [comment]
OK, thanks for explaining 😄
