### ISSUE TITLE
Catch2 version is too old for glibc >= 2.34

### ISSUE THREAD

**Issue by nilsfriess** [codeplaysoftware/syclacademy#124]
Hello,

compilation of the first example with `hipsycl` and clang version 13 fails with [this output](https://github.com/codeplaysoftware/syclacademy/files/8457097/compile_output.txt).
This seems to be caused by a bug in Catch2 (see catchorg/Catch2#2178) that has already been fixed, so updating the Catch2 submodule to newer commit should fix this.

Cheers,
Nils

**Comment by rodburns** [comment]
Thanks for the report Nils. We'll take a look and make an update if everything looks good.

**Comment by rodburns** [comment]
Thanks for the follow up. I believe this was updated last year but it looks like things have got out of sync again.
