### ISSUE TITLE
Questions about SYCL_ACADEMY_ENABLE_SOLUTIONS

### ISSUE THREAD

**Issue by Austin-Hu** [codeplaysoftware/syclacademy#17]
When following up the SYCL Academy lesson, such as the 2nd [example](https://github.com/codeplaysoftware/syclacademy/blob/master/Code_Exercises/Exercise_2_Configuring_a_Queue/doc.md), I got the unexpected output after running the compiled binary (sycl-ex-2) from Intel DevCloud:

_===============================================================================
All tests passed (1 assertion in 1 test case)_

Because the binary should be built from solution.cpp. So:
1. Is it better to turn on SYCL_ACADEMY_ENABLE_SOLUTIONS in [CMakeLists.txt](https://github.com/codeplaysoftware/syclacademy/blob/master/CMakeLists.txt)?
2. (For DPC++), shall we change the building command line from "source.cpp" to "solution.cpp", in each Code_Exercises?

BTW, I didn't verify the change impact for either ComputeCpp or hipSYCL.

Thanks!

**Comment by Austin-Hu** [comment]
Maybe solution.cpp of each Code_Exercises is the example the I (as beginner) can refer to, and source.cpp is the one I can try my own to start with, correct?

**Comment by Austin-Hu** [comment]
The description in the 1st page:
_Each exercise has a markdown document instructing what to do in the exercise, a source file to start with and a solution file to provide an example implementation to compare against._

So close it.

**Comment by rodburns** [comment]
Thanks, maybe it needs to be a bit clearer, I will have a think about it anyway.
