### ISSUE TITLE
Figure in Lesson 11 has 3 times `Data B` in a figure

### ISSUE THREAD

**Issue by keryell** [codeplaysoftware/syclacademy#216]
In file `iwocl23`  `syclacademy/Lesson_Materials/Lecture_11_In_Order_Queue/in_order_diamond_data_flow.png`.
I do not know how to edit `in_order_diamond_data_flow.drawio`.
It should be `Data C` and `Data D`.

**Comment by keryell** [comment]
@rodburns @hdelan

**Comment by hdelan** [comment]
https://github.com/codeplaysoftware/syclacademy/pull/219

**Comment by keryell** [comment]
Thanks.
