### ISSUE TITLE
Trying to getting started with compiling DPC++ but an error occurs

### ISSUE THREAD

**Issue by orobsonlourenco** [codeplaysoftware/syclacademy#324]
I followed the steps but the cloned repository is incomplete, there is no such file named 'source.cpp'.

I used the comand as following:

icpx -fsycl -I ~/syclacademy/External/Catch2/single_include -o a.out source.cpp

Message error was:

icpx: error: no such file or directory: 'source.cpp'
icpx: error: no input files

Does someone knows how to solve this?

**Comment by DuncanMcBain** [comment]
Hi @orobsonlourenco,

this instruction is a general guide for how to compile any given sample, you will need to point the compiler to the exact source file in each case as you go through and complete the tasks.

**Comment by rodburns** [comment]
The build instructions are a general guide, you will need to adapt the command to point to the source file you would like to compile. Let us know if we can improve the guidance to help.
